# Generated by Django 2.2.2 on 2019-07-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190705_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='user12',
        ),
    ]
