# Generated by Django 2.2.2 on 2019-07-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190705_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user12',
            new_name='user',
        ),
    ]
